import { Box, useTheme } from "@mui/material";

export function PropertyPlaceholderImage() {
  const theme = useTheme();

  return (
    <Box
      sx={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.palette.grey[100],
        background: `linear-gradient(135deg, ${theme.palette.grey[100]} 0%, ${theme.palette.grey[200]} 100%)`,
      }}
    >
      <svg
        width="100%"
        height="100%"
        viewBox="0 0 400 240"
        xmlns="http://www.w3.org/2000/svg"
        style={{ display: "block" }}
      >
        <defs>
          <linearGradient id="skyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop
              offset="0%"
              stopColor={theme.palette.primary.light || "#E3F2FD"}
            />
            <stop
              offset="100%"
              stopColor={theme.palette.grey[200] || "#EEEEEE"}
            />
          </linearGradient>
        </defs>
        {/* Céu */}
        <rect width="400" height="240" fill="url(#skyGradient)" />

        {/* Prédio 1 (esquerda) */}
        <rect
          x="40"
          y="100"
          width="60"
          height="140"
          fill={theme.palette.grey[400]}
        />
        <rect
          x="45"
          y="105"
          width="50"
          height="135"
          fill={theme.palette.grey[300]}
        />
        {/* Janelas prédio 1 */}
        <rect
          x="50"
          y="120"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="68"
          y="120"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="86"
          y="120"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="50"
          y="145"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="68"
          y="145"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="86"
          y="145"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="50"
          y="170"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="68"
          y="170"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="86"
          y="170"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />

        {/* Prédio 2 (centro-esquerda) */}
        <rect
          x="120"
          y="60"
          width="70"
          height="180"
          fill={theme.palette.grey[500]}
        />
        <rect
          x="125"
          y="65"
          width="60"
          height="175"
          fill={theme.palette.grey[400]}
        />
        {/* Janelas prédio 2 */}
        <rect
          x="132"
          y="80"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="152"
          y="80"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="172"
          y="80"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="132"
          y="108"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="152"
          y="108"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="172"
          y="108"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="132"
          y="136"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="152"
          y="136"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="172"
          y="136"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="132"
          y="164"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="152"
          y="164"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />
        <rect
          x="172"
          y="164"
          width="14"
          height="18"
          fill={theme.palette.primary.light}
        />

        {/* Prédio 3 (centro-direita) */}
        <rect
          x="210"
          y="80"
          width="65"
          height="160"
          fill={theme.palette.grey[400]}
        />
        <rect
          x="215"
          y="85"
          width="55"
          height="155"
          fill={theme.palette.grey[300]}
        />
        {/* Janelas prédio 3 */}
        <rect
          x="222"
          y="100"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="240"
          y="100"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="258"
          y="100"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="222"
          y="125"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="240"
          y="125"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="258"
          y="125"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="222"
          y="150"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="240"
          y="150"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="258"
          y="150"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="222"
          y="175"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="240"
          y="175"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="258"
          y="175"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />

        {/* Prédio 4 (direita) */}
        <rect
          x="295"
          y="90"
          width="55"
          height="150"
          fill={theme.palette.grey[500]}
        />
        <rect
          x="300"
          y="95"
          width="45"
          height="145"
          fill={theme.palette.grey[400]}
        />
        {/* Janelas prédio 4 */}
        <rect
          x="307"
          y="110"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="325"
          y="110"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="307"
          y="135"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="325"
          y="135"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="307"
          y="160"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="325"
          y="160"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="307"
          y="185"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />
        <rect
          x="325"
          y="185"
          width="12"
          height="15"
          fill={theme.palette.primary.light}
        />

        {/* Nuvens decorativas */}
        <ellipse
          cx="80"
          cy="40"
          rx="25"
          ry="15"
          fill={theme.palette.common.white}
          opacity="0.6"
        />
        <ellipse
          cx="320"
          cy="50"
          rx="30"
          ry="18"
          fill={theme.palette.common.white}
          opacity="0.6"
        />
      </svg>
    </Box>
  );
}

